FROM eclipse-temurin:17-jre AS builder
WORKDIR /extracted
COPY target/*.jar app.jar
RUN java -Djarmode=tools -jar app.jar extract

FROM eclipse-temurin:17-jre
WORKDIR /application
COPY --from=builder /extracted/ ./
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]